language: node_js
node_js:
  - "10" 
branches:
  only:
    - master
script:
  - "yarn run lint"
  - "yarn test"

install:
  - npm install -g firebase-tools
  - npm install && npm run build

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then firebase deploy --token $FIREBASE_TOKEN; fi'